# Generated by Django 5.0.2 on 2026-02-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='medical_registration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
