// Lista completa de departamentos y principales ciudades de Perú
export const peruCities = [
  // Departamentos principales
  'Amazonas',
  'Áncash',
  'Apurímac',
  'Arequipa',
  'Ayacucho',
  'Cajamarca',
  'Callao',
  'Cusco',
  'Huancavelica',
  'Huánuco',
  'Ica',
  'Junín',
  'La Libertad',
  'Lambayeque',
  'Lima',
  'Loreto',
  'Madre de Dios',
  'Moquegua',
  'Pasco',
  'Piura',
  'Puno',
  'San Martín',
  'Tacna',
  'Tumbes',
  'Ucayali',
  
  // Principales ciudades
  'Lima Centro',
  'Arequipa Centro',
  'Callao',
  'Trujillo',
  'Chiclayo',
  'Iquitos',
  'Cusco',
  'Piura',
  'Ayacucho',
  'Huancayo',
  'Tacna',
  'Huánuco',
  'Puno',
  'Cajamarca',
  'Juliaca',
  'Chincha Alta',
  'Pucallpa',
  'Puerto Maldonado',
  'Tingo María',
  'La Merced',
  'Satipo',
  'Moquegua',
  'Nazca',
  'Ica Centro',
  'San Isidro',
  'Miraflores',
  'San Miguel',
  'La Victoria',
  'Rímac',
  'San Juan de Lurigancho',
  'Comas',
  'Ate Vitarte',
  'Villa María del Triunfo',
  'Puente Piedra',
  'Los Olivos',
  'San Juan de Miraflores',
  'Chorrillos',
  'Barranco',
  'Surquillo',
  'Carabayllo',
  'Chaclacayo',
  'San Antonio de Padua',
  'Lurín',
  'Villa El Salvador',
];
